//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOMTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTMENTTABLE
    {
        public DEPARTMENTTABLE()
        {
            this.DETAILSTABLE = new HashSet<DETAILSTABLE>();
        }
    
        public decimal KEY { get; set; }
        public string DEPARTMENT { get; set; }
    
        public virtual ICollection<DETAILSTABLE> DETAILSTABLE { get; set; }
    }
}
