//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOMTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETAILSTABLE
    {
        public DETAILSTABLE()
        {
            this.MEETINGTABLE = new HashSet<MEETINGTABLE>();
        }
    
        public decimal UNIQUEID { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public decimal DEPARTMENT { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE { get; set; }
        public string TELEPHONE { get; set; }
        public decimal ROLE { get; set; }
    
        public virtual DEPARTMENTTABLE DEPARTMENTTABLE { get; set; }
        public virtual ICollection<MEETINGTABLE> MEETINGTABLE { get; set; }
        public virtual ROLETABLE ROLETABLE { get; set; }
    }
}
