//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOMTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAILTIMER
    {
        public decimal KEYID { get; set; }
        public Nullable<decimal> DAYS { get; set; }
        public string TEXT { get; set; }
    }
}
