//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOMTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEETINGTABLE
    {
        public MEETINGTABLE()
        {
            this.AGENDATABLE = new HashSet<AGENDATABLE>();
            this.INVITEESTABLE = new HashSet<INVITEESTABLE>();
        }
    
        public decimal MEETINGID { get; set; }
        public System.DateTime MEETINGDATE { get; set; }
        public string TIME { get; set; }
        public decimal CHAIRPERSON { get; set; }
        public string TITLE { get; set; }
    
        public virtual ICollection<AGENDATABLE> AGENDATABLE { get; set; }
        public virtual DETAILSTABLE DETAILSTABLE { get; set; }
        public virtual ICollection<INVITEESTABLE> INVITEESTABLE { get; set; }
    }
}
