//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOMTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOMDETAILS
    {
        public decimal KEY { get; set; }
        public string CURRENTSTAGE { get; set; }
        public string REMARKS { get; set; }
        public System.DateTime TARGET { get; set; }
        public string ITSPOC { get; set; }
        public string TASKDESCRIPTION { get; set; }
        public string RESPONSIBILITY { get; set; }
        public string ATR { get; set; }
        public Nullable<decimal> MOMDETAILS1 { get; set; }
        public string ACTIONPOINT { get; set; }
        public string EMAIL { get; set; }
    }
}
