//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOMTracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOMDETAILS
    {
        public decimal KEY { get; set; }
        public string STATUS { get; set; }
        public string STATUSREM { get; set; }
        public System.DateTime EXPECTEDCLOSURE { get; set; }
        public string RESP { get; set; }
        public string ACTIONABLE { get; set; }
        public System.DateTime REVIEWDATE { get; set; }
        public string ITEM { get; set; }
    }
}
