//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MOMTracker
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MOMEntities : DbContext
    {
        public MOMEntities()
            : base("name=MOMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AGENDATABLE> AGENDATABLE { get; set; }
        public DbSet<DEPARTMENTTABLE> DEPARTMENTTABLE { get; set; }
        public DbSet<DETAILSTABLE> DETAILSTABLE { get; set; }
        public DbSet<INVITEESTABLE> INVITEESTABLE { get; set; }
        public DbSet<MEETINGTABLE> MEETINGTABLE { get; set; }
        public DbSet<ROLETABLE> ROLETABLE { get; set; }
        public DbSet<MOMDETAILS> MOMDETAILS { get; set; }
        public DbSet<MEMBERTABLE> MEMBERTABLE { get; set; }
    }
}
